---
ROLE_VIEW:
  description: null
  createdDate: "2018-03-30T14:23:03.822Z"
  createdBy: "demo"
  updatedDate: "2018-03-31T08:21:26.680Z"
  updatedBy: "demo"
ROLE_ANONYMOUS:
  description: null
  createdDate: "2018-03-30T14:23:03.822Z"
  createdBy: "demo"
  updatedDate: "2018-03-31T08:21:26.680Z"
  updatedBy: "demo"
